# SPDX-FileCopyrightText: 2024 Stichting Health-RI
#
# SPDX-License-Identifier: Apache-2.0
version: "3"
services:
  solr:
    image: ghcr.io/genomicdatainfrastructure/gdi-userportal-solr:1.1.2
    volumes:
      - ${WEBAPP_STORAGE_HOME}/solr_data:/var/solr
    restart: unless-stopped
