### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

GET http://catalogue.local.onemilliongenomes.eu/api/3/action/package_search?facet.field=["organization","theme","conforms_to","has_version","access_rights","language","publisher_name","res_format","provenance"]&rows=10
